#!/bin/bash

if [ -z $1 ] || [ -z $2 ]
then
    echo "Usage: $(basename $0) <inputblend> <outputavi>"
    exit
fi

blend=$1
movie=$2
rsync $blend cav2@dione:/tmp/$blend
ssh -t dione blender -b /tmp/$blend -F AVIJPEG -o /tmp/$movie -t 8 -a
rsync cav2@dione:/tmp/$movie $movie

