#pragma once

#include <array>
#include <cstddef>

#include <Eigen/Core>
#include <Eigen/Geometry>

namespace ompl::robots
{
    /// A 6-DoF Universal Robots UR5 with its links approximated by spheres.
    ///
    /// This is the robot-side half of the CBF primitive: for each collision
    /// sphere i with radius r_i and center p_i(q), a workspace signed distance
    /// field gives the barrier
    ///
    ///     h_i(q) = d(p_i(q)) - r_i
    ///
    /// and this class supplies both p_i(q) and the exact Jacobian dp_i/dq, so
    /// the barrier derivative follows by the chain rule:
    ///
    ///     dh_i/dq = grad d(p_i)^T * (dp_i/dq)
    ///
    /// Everything is closed form in one pass down the kinematic chain (no
    /// numerical differentiation), and the only dependency is Eigen.
    ///
    /// Sphere model
    /// ------------
    /// The 40 spheres are lifted verbatim from VAMP's hand-authored
    /// `ur5_spherized.urdf`, so this model and VAMP's planner see the same
    /// collision geometry. Each sphere is attached to one of 7 frames — the base
    /// plus the 6 links moved by the 6 revolute joints. The 17 spheres covering
    /// the force/torque sensor and the Robotiq 85 gripper are joined to the arm
    /// by *fixed* joints, so their centers are pre-expressed in `wrist_3_link`'s
    /// frame; they simply ride along with the wrist. See
    /// `scripts/generate_ur5_spheres.py`, which derives the table below from the
    /// URDF and cross-validates it against `vamp.ur5.fk`.
    ///
    /// Frames
    /// ------
    /// Poses are reported in the frame of `basePose`'s parent. The default
    /// `vampBasePose()` reproduces VAMP's ur5.urdf setup — the arm sitting on a
    /// 0.9144 m pedestal, yawed 1.57 rad — which puts sphere centers in exactly
    /// the coordinates `vamp.ur5.fk` reports and VAMP's benchmark scenes use.
    /// Pass `Eigen::Isometry3d::Identity()` to work in `base_link` coordinates
    /// instead, or any other transform to mount the arm somewhere else.
    class UR5
    {
    public:
        static constexpr std::size_t nJoints = 6;
        static constexpr std::size_t nSpheres = 40;
        /// base_link plus the 6 links moved by the joints. Frame f is moved by
        /// joints 0..f-1, so frame 0 never moves.
        static constexpr std::size_t nFrames = 7;

        using Configuration = Eigen::Matrix<double, nJoints, 1>;
        /// d(point)/dq for a single workspace point: 3 rows, one column per joint.
        using PositionJacobian = Eigen::Matrix<double, 3, nJoints>;
        using SphereCenters = Eigen::Matrix<double, 3, nSpheres>;

        /// One collision sphere, rigidly attached to frame `frame`.
        struct Sphere
        {
            std::size_t frame;
            Eigen::Vector3d center;  ///< in `frame`'s coordinates
            double radius;
            const char *link;  ///< URDF link it was authored on, for debugging
        };

        /// Forward kinematics evaluated at one configuration.
        ///
        /// `rotation`/`translation` place a point given in frame f into world
        /// coordinates. `jointOrigin`/`jointAxis` are the world-frame position and
        /// rotation axis of each joint — the two things a position Jacobian column
        /// needs.
        struct Kinematics
        {
            std::array<Eigen::Matrix3d, nFrames> rotation;
            std::array<Eigen::Vector3d, nFrames> translation;
            std::array<Eigen::Vector3d, nJoints> jointOrigin;
            std::array<Eigen::Vector3d, nJoints> jointAxis;
        };

        explicit UR5(const Eigen::Isometry3d &basePose = vampBasePose()) : basePose_(basePose)
        {
        }

        /// The fixed `offset_link -> base_link` hop in VAMP's ur5.urdf: a 0.9144 m
        /// pedestal with a 1.57 rad yaw. This is the default base pose, so sphere
        /// centers match `vamp.ur5.fk` and VAMP's scenes out of the box.
        static Eigen::Isometry3d vampBasePose()
        {
            Eigen::Isometry3d pose = Eigen::Isometry3d::Identity();
            pose.linear() = Eigen::AngleAxisd(1.57, Eigen::Vector3d::UnitZ()).toRotationMatrix();
            pose.translation() = Eigen::Vector3d(0.0, 0.0, 0.9144);
            return pose;
        }

        const Eigen::Isometry3d &basePose() const
        {
            return basePose_;
        }

        /// The sphere approximation of the links: 40 (frame, center, radius) triples.
        static const std::array<Sphere, nSpheres> &spheres()
        {
            // Generated by scripts/generate_ur5_spheres.py from
            // vamp/resources/ur5/ur5_spherized.urdf. Do not hand-edit.
            static const std::array<Sphere, nSpheres> table{{
                // clang-format off
                {0, {0.0, 0.0, 0.0}, 0.08, "base_link"},
                {1, {0.0, 0.0, 0.0}, 0.08, "shoulder_link"},
                {2, {0.0, 0.0, 0.105}, 0.08, "upper_arm_link"},
                {2, {0.0, 0.0, 0.21}, 0.08, "upper_arm_link"},
                {2, {0.0, 0.0, 0.315}, 0.08, "upper_arm_link"},
                {2, {0.0, 0.0, 0.42}, 0.08, "upper_arm_link"},
                {2, {0.0, 0.0, 0.0}, 0.08, "upper_arm_link"},
                {3, {0.0, 0.0, 0.0}, 0.08, "forearm_link"},
                {3, {0.0, 0.0, 0.1}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.14}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.18}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.21999999999999997}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.25999999999999995}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.3}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.34}, 0.04, "forearm_link"},
                {3, {0.0, 0.0, 0.38000000000000006}, 0.04, "forearm_link"},
                {4, {0.0, 0.09, 0.03}, 0.04, "wrist_1_link"},
                {4, {0.0, 0.09, -0.03}, 0.04, "wrist_1_link"},
                {4, {0.0, 0.09, 0.0}, 0.04, "wrist_1_link"},
                {5, {0.0, 0.03, 0.09}, 0.04, "wrist_2_link"},
                {5, {0.0, -0.03, 0.09}, 0.04, "wrist_2_link"},
                {5, {0.0, 0.0, 0.09}, 0.04, "wrist_2_link"},
                {6, {0.0, 0.06, 0.0}, 0.04, "wrist_3_link"},
                {6, {1.5926561138124373e-05, 0.09730000634133472, 0.0}, 0.04, "fts_robotside"},
                {6, {-4.777941697950423e-05, 0.17729996195191194, 0.0005477796026439954}, 0.04, "robotiq_85_base_link"},
                {6, {-1.5926430445582725e-05, 0.13729998731730397, 0.0005159265342146654}, 0.04, "robotiq_85_base_link"},
                {6, {0.03055113195505351, 0.18011634490469636, 0.0005500029597762315}, 0.02, "robotiq_85_left_knuckle_link"},
                {6, {0.06221185321003585, 0.21820759337657858, 0.0005803159612080763}, 0.015, "robotiq_85_left_finger_link"},
                {6, {0.06224370619656978, 0.17820761874197064, 0.0005484628927787463}, 0.015, "robotiq_85_left_finger_link"},
                {6, {0.062227779703302816, 0.19820760605927462, 0.0005643894269934113}, 0.015, "robotiq_85_left_finger_link"},
                {6, {0.03262887193001728, 0.2066334831917182, 0.0005711179477187814}, 0.02, "robotiq_85_left_inner_knuckle_link"},
                {6, {0.04717396614483508, 0.25714208519804244, 0.0006113300730649224}, 0.015, "robotiq_85_left_finger_tip_link"},
                {6, {0.047193874261418786, 0.23214210105141242, 0.0005914219052965894}, 0.015, "robotiq_85_left_finger_tip_link"},
                {6, {-0.032771107333818245, 0.20658140354229462, 0.0005711179477187744}, 0.02, "robotiq_85_right_inner_knuckle_link"},
                {6, {-0.046917649399262115, 0.25742752614889924, 0.0006116170441051241}, 0.015, "robotiq_85_right_finger_tip_link"},
                {6, {-0.04689774128267841, 0.23242754200226923, 0.0005917088763367911}, 0.015, "robotiq_85_right_finger_tip_link"},
                {6, {-0.030651137491679723, 0.18006760799717728, 0.0005500029597762315}, 0.02, "robotiq_85_right_knuckle_link"},
                {6, {-0.06239129616120959, 0.2184409760144585, 0.0005805808252547159}, 0.015, "robotiq_85_right_finger_link"},
                {6, {-0.06235944317467567, 0.17844100137985053, 0.000548727756825379}, 0.015, "robotiq_85_right_finger_link"},
                {6, {-0.06237536966794264, 0.1984409886971545, 0.000564654291040044}, 0.015, "robotiq_85_right_finger_link"},
                // clang-format on
            }};
            return table;
        }

        /// Sphere radii in the order `spheres()` lists them — the r_i in h_i = d - r_i.
        static const Eigen::Matrix<double, nSpheres, 1> &radii()
        {
            static const Eigen::Matrix<double, nSpheres, 1> values = []
            {
                Eigen::Matrix<double, nSpheres, 1> r;
                for (std::size_t i = 0; i < nSpheres; ++i)
                    r[static_cast<Eigen::Index>(i)] = spheres()[i].radius;
                return r;
            }();
            return values;
        }

        /// Joint limits from VAMP's ur5.urdf (+/- pi on every joint).
        static Configuration lowerBounds()
        {
            return Configuration::Constant(-3.14159265);
        }

        static Configuration upperBounds()
        {
            return Configuration::Constant(3.14159265);
        }

        /// Joint velocity limits from VAMP's ur5.urdf (0.5 rad/s on every joint).
        static Configuration velocityLimits()
        {
            return Configuration::Constant(0.5);
        }

        /// A box enclosing every collision sphere's *surface* at every reachable
        /// configuration, in the same frame as `basePose`.
        ///
        /// Size a workspace signed distance field to at least this, or larger: a
        /// `sdf::GridSDF` clamps queries outside its box and so *over*-reports
        /// clearance, which silently invalidates any barrier built on it. The arm
        /// reaches further than it looks — 1.13 m in cylindrical radius, and from
        /// below the pedestal top up to 2.12 m — so a box drawn around a few
        /// hand-picked configurations will not do.
        ///
        /// Measured over 200k uniformly sampled configurations with the default
        /// (VAMP pedestal) base pose, then padded; recompute if `basePose` differs.
        static Eigen::AlignedBox3d reachableBounds()
        {
            return Eigen::AlignedBox3d(Eigen::Vector3d(-1.15, -1.15, -0.15),
                                       Eigen::Vector3d(1.15, 1.15, 2.20));
        }

        /// Walk the chain once, filling in every frame pose and joint axis.
        void kinematics(const Configuration &q, Kinematics &out) const
        {
            Eigen::Matrix3d rotation = basePose_.linear();
            Eigen::Vector3d translation = basePose_.translation();
            out.rotation[0] = rotation;
            out.translation[0] = translation;

            for (std::size_t i = 0; i < nJoints; ++i)
            {
                const JointOrigin &origin = jointOrigins()[i];
                translation += rotation * origin.translation;
                rotation *= origin.rotation;

                // The joint's frame, before its own rotation is applied: this is
                // the point and axis the Jacobian column pivots about.
                out.jointOrigin[i] = translation;
                out.jointAxis[i] = rotation * origin.axis;

                rotation *= Eigen::AngleAxisd(q[static_cast<Eigen::Index>(i)], origin.axis).toRotationMatrix();
                out.rotation[i + 1] = rotation;
                out.translation[i + 1] = translation;
            }
        }

        Kinematics kinematics(const Configuration &q) const
        {
            Kinematics out;
            kinematics(q, out);
            return out;
        }

        /// World-frame pose of one of the `nFrames` kinematic frames.
        static Eigen::Isometry3d framePose(const Kinematics &kin, std::size_t frame)
        {
            Eigen::Isometry3d pose = Eigen::Isometry3d::Identity();
            pose.linear() = kin.rotation[frame];
            pose.translation() = kin.translation[frame];
            return pose;
        }

        /// World-frame pose of the tool flange (`wrist_3_link`).
        static Eigen::Isometry3d endEffectorPose(const Kinematics &kin)
        {
            return framePose(kin, nFrames - 1);
        }

        /// World-frame center of sphere `i` — the p_i(q) in h_i(q) = d(p_i(q)) - r_i.
        static Eigen::Vector3d sphereCenter(const Kinematics &kin, std::size_t i)
        {
            const Sphere &sphere = spheres()[i];
            return kin.translation[sphere.frame] + kin.rotation[sphere.frame] * sphere.center;
        }

        /// All 40 sphere centers, one per column.
        static void sphereCenters(const Kinematics &kin, SphereCenters &out)
        {
            for (std::size_t i = 0; i < nSpheres; ++i)
                out.col(static_cast<Eigen::Index>(i)) = sphereCenter(kin, i);
        }

        SphereCenters sphereCenters(const Configuration &q) const
        {
            SphereCenters out;
            sphereCenters(kinematics(q), out);
            return out;
        }

        /// Exact d(center_i)/dq. Column k is the standard revolute-joint term
        /// axis_k x (p_i - origin_k) for the joints upstream of sphere i, and zero
        /// for the joints downstream of it (they cannot move it).
        static PositionJacobian sphereJacobian(const Kinematics &kin, std::size_t i)
        {
            const std::size_t frame = spheres()[i].frame;
            const Eigen::Vector3d p = sphereCenter(kin, i);

            PositionJacobian jacobian = PositionJacobian::Zero();
            for (std::size_t k = 0; k < frame; ++k)  // frame f is moved by joints 0..f-1
                jacobian.col(static_cast<Eigen::Index>(k)) = kin.jointAxis[k].cross(p - kin.jointOrigin[k]);
            return jacobian;
        }

        /// Gradient of h_i = d(p_i(q)) - r_i with respect to q, given the workspace
        /// SDF gradient at the sphere center. This is the row a CBF constraint on
        /// sphere i contributes; `sdfGradient` comes straight from
        /// `ompl::sdf::GridSDF::gradient()`.
        static Configuration barrierGradient(const Kinematics &kin, std::size_t i,
                                             const Eigen::Vector3d &sdfGradient)
        {
            return sphereJacobian(kin, i).transpose() * sdfGradient;
        }

    private:
        /// One URDF `<joint>`: the fixed parent-to-child offset, then a rotation
        /// about `axis` by that joint's value.
        struct JointOrigin
        {
            Eigen::Matrix3d rotation;
            Eigen::Vector3d translation;
            Eigen::Vector3d axis;
        };

        /// The six revolute joints of VAMP's ur5.urdf, in chain order. Note the
        /// axes are not all Z: this URDF uses z, y, y, y, z, y.
        static const std::array<JointOrigin, nJoints> &jointOrigins()
        {
            static const std::array<JointOrigin, nJoints> origins = []
            {
                // <origin rpy="r p y"/> is R = Rz(y) Ry(p) Rx(r); every UR5 joint
                // origin here has only a pitch component, so Ry alone suffices.
                const auto pitch = [](double angle)
                { return Eigen::AngleAxisd(angle, Eigen::Vector3d::UnitY()).toRotationMatrix(); };
                const Eigen::Matrix3d none = Eigen::Matrix3d::Identity();
                const Eigen::Vector3d z = Eigen::Vector3d::UnitZ();
                const Eigen::Vector3d y = Eigen::Vector3d::UnitY();
                constexpr double halfPi = 1.570796325;  // as spelled in the URDF

                return std::array<JointOrigin, nJoints>{{
                    {none, {0.0, 0.0, 0.089159}, z},          // shoulder_pan_joint
                    {pitch(halfPi), {0.0, 0.13585, 0.0}, y},  // shoulder_lift_joint
                    {none, {0.0, -0.1197, 0.425}, y},         // elbow_joint
                    {pitch(halfPi), {0.0, 0.0, 0.39225}, y},  // wrist_1_joint
                    {none, {0.0, 0.093, 0.0}, z},             // wrist_2_joint
                    {none, {0.0, 0.0, 0.09465}, y},           // wrist_3_joint
                }};
            }();
            return origins;
        }

        Eigen::Isometry3d basePose_;
    };
}  // namespace ompl::robots
