string(REPLACE "\\\ " " " dir "${dir}")
file(READ "${dir}/py-bindings/headers_${module}.txt" headers_string)
separate_arguments(headers UNIX_COMMAND "${headers_string}")
set(module_header "bindings/${module}.h")
file(WRITE "${module_header}" "")
foreach(header ${headers})
    if(NOT exclude OR NOT header MATCHES "${exclude}")
        file(READ "${dir}/${header}" _header_txt)
        file(APPEND "${module_header}" "${_header_txt}")
    endif()
endforeach(header)
