# set the version in a way CMake can use
set(OMPL_MAJOR_VERSION 0)
set(OMPL_MINOR_VERSION 9)
set(OMPL_PATCH_VERSION 4)
set(OMPL_VERSION "${OMPL_MAJOR_VERSION}.${OMPL_MINOR_VERSION}.${OMPL_PATCH_VERSION}")
