// autogenerated forward declaration header
#pragma once
#include <memory>
namespace sco
{
    class GurobiModel;
    typedef std::shared_ptr<GurobiModel> GurobiModelPtr;
    class ConvexObjective;
    typedef std::shared_ptr<ConvexObjective> ConvexObjectivePtr;
    class ConvexConstraints;
    typedef std::shared_ptr<ConvexConstraints> ConvexConstraintsPtr;
    class Cost;
    typedef std::shared_ptr<Cost> CostPtr;
    class Constraint;
    typedef std::shared_ptr<Constraint> ConstraintPtr;
    class EqConstraint;
    typedef std::shared_ptr<EqConstraint> EqConstraintPtr;
    class IneqConstraint;
    typedef std::shared_ptr<IneqConstraint> IneqConstraintPtr;
    class OptProb;
    typedef std::shared_ptr<OptProb> OptProbPtr;
    class CostFromFunc;
    typedef std::shared_ptr<CostFromFunc> CostFromFuncPtr;
    class ConstraintFromFunc;
    typedef std::shared_ptr<ConstraintFromFunc> ConstraintFromFuncPtr;
    class Optimizer;
    typedef std::shared_ptr<Optimizer> OptimizerPtr;
    class BasicTrustRegionSQP;
    typedef std::shared_ptr<BasicTrustRegionSQP> BasicTrustRegionSQPPtr;
    class Model;
    typedef std::shared_ptr<Model> ModelPtr;
    struct VarRep;
    typedef std::shared_ptr<VarRep> VarRepPtr;
    struct Var;
    typedef std::shared_ptr<Var> VarPtr;
    struct CntRep;
    typedef std::shared_ptr<CntRep> CntRepPtr;
    struct Cnt;
    typedef std::shared_ptr<Cnt> CntPtr;
    struct AffExpr;
    typedef std::shared_ptr<AffExpr> AffExprPtr;
    struct QuadExpr;
    typedef std::shared_ptr<QuadExpr> QuadExprPtr;
}
