/*********************************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2017, Rice University
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Rice University nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 *********************************************************************/

/* Author: Clayton W. Ramsey */

// Generates flat_steering_reference.txt, the minimum-effort steering data that
// tests/base/flat_motion.cpp checks ompl::base::MinimumEffortSteering against.
//
// The values come from the FLASK implementation in flask-private, which is a separate private
// repository, so this file builds out of tree and its output is committed beside it.
// Build it with
//
//   g++ -std=c++17 -O2 -mavx2 -mfma -DNDEBUG -w \
//       -I<flask-private>/src/impl -I/usr/include/eigen3 -I<nigh>/src \
//       -o generate_flat_steering_reference generate_flat_steering_reference.cpp
//
// and run it with the output path as its only argument.
// FLASK computes in single precision, so every recorded value is a float and the test compares to a
// loose tolerance.
//
// The random draws come straight from the engine rather than from a distribution object, so the same
// seed gives the same cases on any standard library.

#include <vamp/planning/poly.hh>

#include <array>
#include <cstdio>
#include <cstdlib>
#include <random>
#include <string>

namespace
{
    constexpr std::size_t dimension = 3;
    constexpr std::size_t samples = 3;
    constexpr std::size_t cases = 2000;
    constexpr float rho = 5.f;

    std::mt19937_64 engine(20260917u);

    float uniform(float low, float high)
    {
        const double unit = static_cast<double>(engine() >> 11) * 0x1.0p-53;
        return static_cast<float>(low + unit * (high - low));
    }

    std::array<float, dimension> drawPosition()
    {
        std::array<float, dimension> values{};
        for (auto &value : values)
            value = uniform(-2.f, 2.f);
        return values;
    }

    std::array<float, dimension> drawVelocity()
    {
        std::array<float, dimension> values{};
        for (auto &value : values)
            value = uniform(-1.f, 1.f);
        return values;
    }

    // Every field goes on after a separating space, so a finished line carries no trailing blank.
    void appendNumber(std::string &line, double value)
    {
        char buffer[32];
        std::snprintf(buffer, sizeof(buffer), "%.9g", value);
        if (!line.empty())
            line.push_back(' ');
        line.append(buffer);
    }

    void appendVector(std::string &line, const std::array<float, dimension> &values)
    {
        for (float value : values)
            appendNumber(line, value);
    }
}  // namespace

int main(int argc, char **argv)
{
    if (argc != 2)
    {
        std::fprintf(stderr, "usage: %s <output path>\n", argv[0]);
        return 1;
    }

    std::FILE *out = std::fopen(argv[1], "w");
    if (out == nullptr)
    {
        std::fprintf(stderr, "cannot open %s\n", argv[1]);
        return 1;
    }

    std::fprintf(out, "# Minimum-effort steering reference data produced by FLASK in single precision.\n");
    std::fprintf(out, "# Generated by generate_flat_steering_reference.cpp, which documents how to rebuild it.\n");
    std::fprintf(out, "# Each case holds y0, v0, yf, vf, a success flag, the duration, the cost, and the flat\n");
    std::fprintf(out, "# output sampled at one quarter, one half, and three quarters of the duration.\n");
    std::fprintf(out, "dimension %zu\nrho %g\nsamples %zu\ncases %zu\n", dimension, rho, samples, cases);

    // Positions come from a box and velocities from a smaller one.
    // Every sixteenth case repeats the start as the goal and every thirty-second repeats its velocity
    // too, so the data covers the coincident endpoints that make the quartic degenerate.
    for (std::size_t index = 0; index < cases; ++index)
    {
        const auto y0 = drawPosition();
        const auto v0 = drawVelocity();
        const auto yf = (index % 16 == 0) ? y0 : drawPosition();
        const auto vf = (index % 32 == 0) ? v0 : drawVelocity();

        std::string line;
        appendVector(line, y0);
        appendVector(line, v0);
        appendVector(line, yf);
        appendVector(line, vf);

        float duration = -1.f;
        auto polynomial = vamp::planning::opt_time_traj<dimension>(
            vamp::FloatVector<dimension>(y0), vamp::FloatVector<dimension>(v0), vamp::FloatVector<dimension>(yf),
            vamp::FloatVector<dimension>(vf), duration);

        if (duration > 0.f)
        {
            appendNumber(line, 1.);
            appendNumber(line, duration);
            appendNumber(line, polynomial.cost(duration, rho));
            for (std::size_t sample = 1; sample <= samples; ++sample)
            {
                const auto value =
                    polynomial.eval(duration * static_cast<float>(sample) / static_cast<float>(samples + 1));
                const auto packed = value.to_array();
                for (std::size_t axis = 0; axis < dimension; ++axis)
                    appendNumber(line, packed[axis]);
            }
        }
        else
        {
            for (std::size_t field = 0; field < 3 + samples * dimension; ++field)
                appendNumber(line, 0.);
        }
        std::fprintf(out, "%s\n", line.c_str());
    }

    std::fclose(out);
    return 0;
}
