#include "init.hh"

NB_MODULE(_control, m)
{
    ompl::binding::control::initPlannersEst_EST(m);
    ompl::binding::control::initPlannersKpiece_KPIECE1(m);
    ompl::binding::control::initPlannersLtl_Automaton(m);
    ompl::binding::control::initPlannersLtl_LTLPlanner(m);
    ompl::binding::control::initPlannersLtl_LTLProblemDefinition(m);
    ompl::binding::control::initPlannersLtl_LTLSpaceInformation(m);
    ompl::binding::control::initPlannersLtl_ProductGraph(m);
    ompl::binding::control::initPlannersLtl_PropositionalDecomposition(m);
    ompl::binding::control::initPlannersLtl_World(m);
    ompl::binding::control::initPlannersPdst_PDST(m);
    ompl::binding::control::initPlannersRrt_RRT(m);
    ompl::binding::control::initPlannersSst_SST(m);
    ompl::binding::control::initPlannersSyclop_Decomposition(m);
    ompl::binding::control::initPlannersSyclop_GridDecomposition(m);
    ompl::binding::control::initPlannersSyclop_Syclop(m);
    ompl::binding::control::initPlannersSyclop_SyclopEST(m);
    ompl::binding::control::initPlannersSyclop_SyclopRRT(m);
    ompl::binding::control::initPlanners_PlannerIncludes(m);
    ompl::binding::control::initSpaces_DiscreteControlSpace(m);
    ompl::binding::control::initSpaces_RealVectorControlSpace(m);
    ompl::binding::control::init_Control(m);
    ompl::binding::control::init_ControlSampler(m);
    ompl::binding::control::init_ControlSpace(m);
    ompl::binding::control::init_ControlSpaceTypes(m);
    ompl::binding::control::init_DirectedControlSampler(m);
    ompl::binding::control::init_ODESolver(m);
    ompl::binding::control::init_PathControl(m);
    ompl::binding::control::init_PlannerData(m);
    ompl::binding::control::init_PlannerDataStorage(m);
    ompl::binding::control::init_SimpleDirectedControlSampler(m);
    ompl::binding::control::init_SimpleSetup(m);
    ompl::binding::control::init_SpaceInformation(m);
    ompl::binding::control::init_StatePropagator(m);
    ompl::binding::control::init_SteeredControlSampler(m);
}
