#!/usr/bin/env python3
"""Flatten VAMP's MotionBenchMaker UR5 problems into a text file the C++ demos read.

The source is ``vamp/resources/ur5/problems.json`` (MotionBenchMaker via robometrics,
700 problems over 7 scenes). Every obstacle there is a box or a cylinder, both of which
have an exact closed-form signed distance, so a scene bakes straight into an
``ompl::sdf::GridSDF`` with no meshes and no FCL.

Emitted format, whitespace separated, one record per line -- deliberately dumb so the
reader is twenty lines of ``std::istream`` rather than a JSON dependency:

    problem <scene> <index>
    start   q0 .. q5
    goal    q0 .. q5
    box     hx hy hz  px py pz  qx qy qz qw
    cyl     radius halfLength  px py pz  qx qy qz qw
    end

Only problems flagged ``valid`` are written. Orientations come from the quaternion
field, not the Euler one, to avoid guessing a convention.

    ./scripts/mbm_to_scenes.py [problems.json] [out.txt]
"""

import json
import sys
from pathlib import Path

DEFAULT_JSON = Path("/home/mani/vamp/resources/ur5/problems.json")


def main() -> int:
    source = Path(sys.argv[1]) if len(sys.argv) > 1 else DEFAULT_JSON
    target = Path(sys.argv[2]) if len(sys.argv) > 2 else Path("ur5_mbm_scenes.txt")

    if not source.is_file():
        print(f"no such file: {source}", file=sys.stderr)
        print("Clone https://github.com/KavrakiLab/vamp and point at "
              "resources/ur5/problems.json", file=sys.stderr)
        return 1

    data = json.loads(source.read_text())
    if data.get("robot") != "ur5":
        print(f"expected a ur5 problem set, got {data.get('robot')!r}", file=sys.stderr)
        return 1

    lines = [f"# generated by scripts/mbm_to_scenes.py from {source}",
             f"# joints: {' '.join(data['joints'])}"]
    counts = {}
    for scene, problems in data["problems"].items():
        written = 0
        for problem in problems:
            if not problem.get("valid"):
                continue
            if len(problem["goals"]) != 1:
                # Every MotionBenchMaker problem has a single goal; a set-valued one
                # would need a GoalStates, which the demos do not build.
                continue
            lines.append(f"problem {scene} {problem['index']}")
            lines.append("start " + " ".join(f"{v:.10g}" for v in problem["start"]))
            lines.append("goal " + " ".join(f"{v:.10g}" for v in problem["goals"][0]))
            for box in problem["box"]:
                h = box["half_extents"]
                p = box["position"]
                q = box["orientation_quat_xyzw"]
                lines.append("box " + " ".join(f"{v:.10g}" for v in (*h, *p, *q)))
            for cylinder in problem["cylinder"]:
                p = cylinder["position"]
                q = cylinder["orientation_quat_xyzw"]
                lines.append("cyl " + " ".join(
                    f"{v:.10g}" for v in (cylinder["radius"], 0.5 * cylinder["length"], *p, *q)))
            for sphere in problem["sphere"]:
                # None of the UR5 scenes use these today; a box with equal half extents
                # is not a sphere, so refuse rather than approximate.
                raise SystemExit(f"{scene}#{problem['index']}: sphere obstacles are not "
                                 f"emitted yet ({sphere.get('name')})")
            lines.append("end")
            written += 1
        counts[scene] = written

    target.write_text("\n".join(lines) + "\n")
    total = sum(counts.values())
    print(f"wrote {total} problems to {target}")
    for scene, n in sorted(counts.items()):
        print(f"  {scene:20s} {n:4d}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
